name: my-project
channels:
  - conda-forge
dependencies:
  - python>=3.13
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - sqlalchemy>=2.0.0
  - pyarrow>=15.0.0
  - psycopg2-binary>=2.9.0
  - pip
  - pip:
    - wget